[package]
name = "guppy"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.31.1"
env_logger = "0.11.8"
gemini-rs = "1.3.0"
serde_json = "1.0.140"
tokio = { version = "1.45.0", features = ["full"] }
winreg = "0.55.0"
